name: Search test running in Cypress

on:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependences
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Report upload
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports